name: Daily Feed Export

on:
  workflow_dispatch:
    inputs:
      logs_date:
        description: 'YYYY-MM-DD to summarize (optional)'
        required: false
      preview_only:
        description: 'Preview only (no sheet write)'
        type: boolean
        required: false
        default: true
      partner_name:
        description: 'Active partner name (substring) to snapshot into LogsPartners (optional)'
        required: false
  schedule:
    - cron: '0 8 * * *'  # runs daily; metrics script summarizes "yesterday" in Europe/Rome

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Rome

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run export script (Feeds)
        env:
          PORTAL_LOGIN_URL: ${{ secrets.PORTAL_LOGIN_URL }}
          PORTAL_FEEDS_URL: ${{ secrets.PORTAL_FEEDS_URL }}
          PORTAL_USER: ${{ secrets.PORTAL_USER }}
          PORTAL_PASS: ${{ secrets.PORTAL_PASS }}
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
        run: python export_feeds.py

      - name: Run daily logs metrics -> Google Sheet
        env:
          PORTAL_LOGIN_URL: ${{ secrets.PORTAL_LOGIN_URL }}
          PORTAL_USER:      ${{ secrets.PORTAL_USER }}
          PORTAL_PASS:      ${{ secrets.PORTAL_PASS }}
          PORTAL_FEEDS_URL: ${{ secrets.PORTAL_FEEDS_URL }}   # used by the logs script to reach the Log buttons
          WEBAPP_URL:       ${{ secrets.WEBAPP_URL }}
          LOGS_DATE:        ${{ github.event.inputs.logs_date }}
          PREVIEW_ONLY:     ${{ github.event.inputs.preview_only }}
        run: python export_logs_daily.py

      - name: Run single-partner log snapshot -> LogsPartners
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.partner_name != '' }}
        env:
          PORTAL_LOGIN_URL: ${{ secrets.PORTAL_LOGIN_URL }}
          PORTAL_FEEDS_URL: ${{ secrets.PORTAL_FEEDS_URL }}
          PORTAL_USER:      ${{ secrets.PORTAL_USER }}
          PORTAL_PASS:      ${{ secrets.PORTAL_PASS }}
          WEBAPP_URL:       ${{ secrets.WEBAPP_URL }}
          TARGET_PARTNER:   ${{ github.event.inputs.partner_name }}
          PREVIEW_ONLY:     ${{ github.event.inputs.preview_only }}
        run: python check_one_log.py
